# .github/workflows/release.yml

name: Release Package

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch:

jobs:
  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci.yml

  release:
    if: ${{ !endsWith(github.repository, 'pnpm-turbo-monorepo-template') }}
    name: Create Release and Publish
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          registry-url: 'https://registry.npmjs.org'
          build: 'false'

      - name: Release
        uses: pixpilot/changesets-autopilot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
# ======================================================================
# If your branch is protected, remove the steps above and use this one instead.
# Additional setup:
# - See the following gist for detailed instructions:
#   https://gist.github.com/0xernesto/a8065cce55940e6ccc523664a87ee9bc
# - You must set up a GitHub App and add the following repository secrets:
#     RELEASER_ID:            The App ID of your GitHub App
#     RELEASER_PRIVATE_KEY:   The private key for your GitHub App
#     NPM_TOKEN:              Your npm publish token
# ======================================================================
# steps:
#   - name: Generate bot app token
#     id: app_token
#     uses: actions/create-github-app-token@v2
#     with:
#       app-id: ${{ secrets.RELEASER_ID }}
#       private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}

#   - name: Checkout repository
#     uses: actions/checkout@v4
#     with:
#       fetch-depth: 0
#       token: ${{ steps.app_token.outputs.token }}

#   - name: Setup project
#     uses: ./.github/actions/setup-project
#     with:
#       registry-url: 'https://registry.npmjs.org'
#       build: 'false'

#   - name: Release
#     uses: pixpilot/changesets-autopilot@v1
#     with:
#       GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
#       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
